version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - './:/var/www'
        networks:
            - laravel
        depends_on:
            - mysql
            - redis
            - mailhog

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog_server
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - laravel

    nginx:
        image: 'nginx:alpine'
        container_name: nginx_server
        ports:
            - '88:80'
        volumes:
            - './:/var/www'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: 'mysql:8.0'
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: personalblog
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - 'mysql-data:/var/lib/mysql'
        ports:
            - '3333:3306'
        networks:
            - laravel

    redis:
        image: 'redis:alpine'
        container_name: redis_server
        ports:
            - '6379:6379'
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql-data: null
